//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutletsApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbТорговыеТочкиEntities : DbContext
    {
        public dbТорговыеТочкиEntities()
            : base("name=dbТорговыеТочкиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Магазины> Магазины { get; set; }
        public virtual DbSet<Номенклатура> Номенклатура { get; set; }
        public virtual DbSet<Специализации> Специализации { get; set; }
        public virtual DbSet<ФормыСобственности> ФормыСобственности { get; set; }
    }
}
