//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutletsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номенклатура
    {
        public int НоменклатураID { get; set; }
        public int МагазинID { get; set; }
        public string НаименованиеТовара { get; set; }
        public int КатегорияID { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Категории Категории { get; set; }
        public virtual Магазины Магазины { get; set; }
    }
}
